export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',

  FORBIDDEN = 'FORBIDDEN',

  NOT_FOUND = 'NOT_FOUND',

  CONFLICT = 'CONFLICT',

  USER_NOT_FOUND = 'USER_NOT_FOUND',

  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',

  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',

  TASK_NOT_FOUND = 'TASK_NOT_FOUND',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
}
